# Site settings
title: Allday Media
tagline: Design. Print. Distribution.
email: wvleaflets@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: pretty
url: "http://wvleaflets.github.io/wvleaflets" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, bower_components, assets, bower.json, gulpfile.js, Gemfile, Gemfile.lock]
collections:
  faq:
    output: false
  pricing:
    output: false
prose:
  ignore:
    - .gitignore
    - CNAME
    - Gemfile
    - Gemfile.lock
    - apple-touch-icon.png
    - favicon.ico
    - robots.txt
    - _config.yml
    - /_layouts
    - /_includes
    - /css
